
server:
  port: 5522
  servlet:
    context-path: /api/v1

spring:
  application:
    name: cmq_consumer

mq:
  tencent:
    nameServerAddress: http://127.0.0.1
    secretId: 10000
    secretKey: 1377
  send:
    queue: QUEUE_XXX
    topic: TOPIC_XXX #暂时没使用